openapi: 3.0.0
info:
  title: Ian's API
  version: 1.0.0
  description: Company API
servers:
  - url: http://143.244.167.138:3000
paths:
  /agents:
    get:
      summary: Get all agents
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string